/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.company;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Vector;
import java.util.logging.Logger;

/**
 *
 * @author szymon
 */
public class QuestionFrame extends javax.swing.JFrame {

    /** Creates new form questionframe */
    public QuestionFrame(QuestionRespository questionRespository,MajorRepository majorRepository) {
        this.questionRespository=questionRespository;
        this.majorRepository=majorRepository;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Pytanie\naaaaaa");

        jButton1.setText("Odp1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Odp2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Odp3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        updateQuestion();
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(93, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        pack();
        this.questionNumber=1;
        this.setTitle("Pytanie "+questionNumber);
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if(actualQuestion.answer[0].equals("tak"))
            majorRepository.riseWeightWhereFeature(actualQuestion.feature,actualQuestion.answer[0]);
        else
            majorRepository.switchFeatures(actualQuestion.feature,actualQuestion.answer[1],actualQuestion.answer[0]);
        updateQuestion();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        if(actualQuestion.answer[0].equals("tak"))
            majorRepository.disableWhereFeature(actualQuestion.feature,actualQuestion.answer[0]);
        else
            majorRepository.switchFeatures(actualQuestion.feature,actualQuestion.answer[0],actualQuestion.answer[1]);

        updateQuestion();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        updateQuestion();
    }


    private void updateQuestion()
    {
        actualQuestion=questionRespository.getNextQuestion();
        if(actualQuestion==null)
        {
            presentResults();
            return;
        }
        jLabel1.setText(actualQuestion.question);
        jButton1.setText(actualQuestion.answer[0]);
        jButton2.setText(actualQuestion.answer[1]);
        jButton3.setText(actualQuestion.answer[2]);
        questionNumber++;
        this.setTitle("Pytanie "+questionNumber);
        this.setVisible(true);
    }

    private void presentResults() {
        List<Major>results=majorRepository.getResults();
        ResultFrame resultFrame=new ResultFrame(this);
        setTable(results,resultFrame);
        resultFrame.setVisible(true);
        resultFrame.setLocation(this.getLocation());
        this.dispose();
    }

    private void setTable(List<Major> resultList, ResultFrame newJFrame) {

        JTable table =newJFrame.getjTable1();
        DefaultTableModel model =(DefaultTableModel)table.getModel();

        for(Major record:resultList)
        {
            Vector vector=new Vector();
            vector.add(record.getName());
            vector.add(record.getUniversity());

            if(record.getFeatureValue("licencjacki").equals("1"))
                vector.add("licencjackie");
            else
                vector.add("inżynierskie");
            if(record.getFeatureValue("jezykWykladowy").equals("angielski"))
                vector.add("Angielski");
            else
                vector.add("Polski");
            model.addRow(vector);

        }
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextArea jLabel1;
    int questionNumber;
    Question actualQuestion;
    MajorRepository majorRepository;
    QuestionRespository questionRespository;

    public void restart() {
        majorRepository.restart();
        questionRespository.restart();
        questionNumber=0;
        updateQuestion();

    }
    // End of variables declaration

}
